version: "3.9"

services:
  database_ptag:
    image: postgres
    container_name: database_ptag
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ptag_root
      - POSTGRES_PASSWORD=ptag152532
      - POSTGRES_DB=ptag_db
    volumes:
      - pgdata:/data/postgres

  app_ptag:
    build: .
    container_name: ptag
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ptag
    depends_on:
      - database_ptag

volumes:
  pgdata:
    driver: local